<?php
// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
// Make sure config is included
require_once "config.php";
require_once "NotesController.php";

// Check if ID is provided
if (!isset($_GET['id']) || empty($_GET['id'])) {
    // Redirect to index if no ID is specified
    header('Location: index.php');
    exit;
}

// Get the note ID from URL
$id = $_GET['id'];

// Initialize the controller
$controller = new NotesController();

// Call the edit method with the ID
$controller->edit($id);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Edit Note</title>
    <!-- Note: The styling is now included in the NotesController::edit method -->
</head>
<body>
    <!-- The form is generated by the controller -->
</body>
</html>